/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as RndRouteImport } from './routes/rnd'
import { Route as ResearchInnovationRouteImport } from './routes/research-innovation'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as GenomicsRouteImport } from './routes/genomics'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BioinformaticsRouteImport } from './routes/bioinformatics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const RndRoute = RndRouteImport.update({
  id: '/rnd',
  path: '/rnd',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchInnovationRoute = ResearchInnovationRouteImport.update({
  id: '/research-innovation',
  path: '/research-innovation',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const GenomicsRoute = GenomicsRouteImport.update({
  id: '/genomics',
  path: '/genomics',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BioinformaticsRoute = BioinformaticsRouteImport.update({
  id: '/bioinformatics',
  path: '/bioinformatics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bioinformatics': typeof BioinformaticsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/genomics': typeof GenomicsRoute
  '/partnerships': typeof PartnershipsRoute
  '/publications': typeof PublicationsRoute
  '/research-innovation': typeof ResearchInnovationRoute
  '/rnd': typeof RndRoute
  '/roadmap': typeof RoadmapRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/training': typeof TrainingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bioinformatics': typeof BioinformaticsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/genomics': typeof GenomicsRoute
  '/partnerships': typeof PartnershipsRoute
  '/publications': typeof PublicationsRoute
  '/research-innovation': typeof ResearchInnovationRoute
  '/rnd': typeof RndRoute
  '/roadmap': typeof RoadmapRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/training': typeof TrainingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bioinformatics': typeof BioinformaticsRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/genomics': typeof GenomicsRoute
  '/partnerships': typeof PartnershipsRoute
  '/publications': typeof PublicationsRoute
  '/research-innovation': typeof ResearchInnovationRoute
  '/rnd': typeof RndRoute
  '/roadmap': typeof RoadmapRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/training': typeof TrainingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bioinformatics'
    | '/blog'
    | '/contact'
    | '/founder'
    | '/genomics'
    | '/partnerships'
    | '/publications'
    | '/research-innovation'
    | '/rnd'
    | '/roadmap'
    | '/services'
    | '/sitemap.xml'
    | '/training'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bioinformatics'
    | '/blog'
    | '/contact'
    | '/founder'
    | '/genomics'
    | '/partnerships'
    | '/publications'
    | '/research-innovation'
    | '/rnd'
    | '/roadmap'
    | '/services'
    | '/sitemap.xml'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bioinformatics'
    | '/blog'
    | '/contact'
    | '/founder'
    | '/genomics'
    | '/partnerships'
    | '/publications'
    | '/research-innovation'
    | '/rnd'
    | '/roadmap'
    | '/services'
    | '/sitemap.xml'
    | '/training'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BioinformaticsRoute: typeof BioinformaticsRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FounderRoute: typeof FounderRoute
  GenomicsRoute: typeof GenomicsRoute
  PartnershipsRoute: typeof PartnershipsRoute
  PublicationsRoute: typeof PublicationsRoute
  ResearchInnovationRoute: typeof ResearchInnovationRoute
  RndRoute: typeof RndRoute
  RoadmapRoute: typeof RoadmapRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrainingRoute: typeof TrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rnd': {
      id: '/rnd'
      path: '/rnd'
      fullPath: '/rnd'
      preLoaderRoute: typeof RndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-innovation': {
      id: '/research-innovation'
      path: '/research-innovation'
      fullPath: '/research-innovation'
      preLoaderRoute: typeof ResearchInnovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genomics': {
      id: '/genomics'
      path: '/genomics'
      fullPath: '/genomics'
      preLoaderRoute: typeof GenomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bioinformatics': {
      id: '/bioinformatics'
      path: '/bioinformatics'
      fullPath: '/bioinformatics'
      preLoaderRoute: typeof BioinformaticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BioinformaticsRoute: BioinformaticsRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FounderRoute: FounderRoute,
  GenomicsRoute: GenomicsRoute,
  PartnershipsRoute: PartnershipsRoute,
  PublicationsRoute: PublicationsRoute,
  ResearchInnovationRoute: ResearchInnovationRoute,
  RndRoute: RndRoute,
  RoadmapRoute: RoadmapRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrainingRoute: TrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
